# syntax=docker/dockerfile:1

FROM gcr.io/distroless/static-debian12:nonroot

ARG TARGETPLATFORM
COPY ${TARGETPLATFORM}/local-pvc-exporter /local-pvc-exporter

USER nonroot:nonroot

EXPOSE 8080

ENTRYPOINT ["/local-pvc-exporter"]
